spring.application.name=module4_s9_muonsach

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=sinh6802
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
